name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install dvc

    - name: Pull data from DVC
      run: dvc pull

    - name: Run Preprocessing Script
      run: python src/data_preprocessing.py

    # - name: Commit processed data
      # run: |
      #   git config --global user.name 'GitHub Actions'
      #   git config --global user.email 'actions@github.com'
      #   dvc add data/processed/merged_data.csv
      #   dvc add data/processed/processed_for_model.csv
      #   git add data/processed/*.dvc
      #   git commit -m 'Update processed data'
      #   git push origin main
